name: Create Guild Op Issues

on:
  push:
    paths:
      - 'archives/input_ops.json'

permissions:
  contents: read
  issues: write

jobs:
  create_issues_from_json:
    runs-on: ubuntu-latest
    env:
      PROJECT_ID: "CCG" # Or your desired default
      CONTEXT_LABEL: "Context:PERS" # Or your desired default
      ASSIGNEE: "Kin-Caid"
      REPO_NAME: ${{ github.repository }}
      OPS_FILE_PATH: "archives/input_ops.json"
      # --- THIS IS THE LINE TO CORRECT ---
      PROMPT_TEMPLATE_PATH: ".github/scripts/prompts/api_brief_generation_prompt.md" 
      GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}

    steps:
      # ... (Checkout, Setup Python, Install Dependencies steps) ...
      
      # Authenticate GitHub CLI step - ensure it's disabled if using PyGithub
      - name: Authenticate GitHub CLI (Skipped if using PyGithub)
        if: ${{ false }} 
        run: echo "Skipping gh auth as PyGithub is used"

      - name: Run Guild Op Processing Script
        run: |
          python .github/scripts/process_ops.py \
            --ops_file "${{ env.OPS_FILE_PATH }}" \
            --project_id "${{ env.PROJECT_ID }}" \
            --context_label "${{ env.CONTEXT_LABEL }}" \
            --assignee "${{ env.ASSIGNEE }}" \
            --repo_name "${{ env.REPO_NAME }}" \
            --prompt_template_path "${{ env.PROMPT_TEMPLATE_PATH }}"
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
