name: Generate Guild Op Briefs for Review

on:
  push:
    paths:
      - 'Projects/input_ops.json'

permissions:
  contents: write

jobs:
  generate_for_review:
    if: "contains(github.event.head_commit.message, '[skip ci]') == false"
    runs-on: ubuntu-latest
    
    env:
      OPS_FILE_PATH: "Projects/input_ops.json"
      GEMINI_MODEL: "gemini-2.5-flash-preview-05-20"
      PROMPT_TEMPLATE_PATH: ".github/scripts/prompts/review_generation_prompt_template.txt" 
      PROJECT_MAPPINGS_FILE: "project_mappings.json"
      BASE_OUTPUT_JSON: "_generated_briefs_to_create.json"
      BASE_OUTPUT_MD: "_generated_briefs_for_review.md"
      GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      
      - name: Install jq (JSON Processor)
        run: sudo apt-get install -y jq

      - name: Read Metadata from JSON and Set Environment
        id: metadata
        run: |
          # This step correctly adds more variables to the job's environment for subsequent steps
          PROJECT_ID_PREFIX=$(jq -r '.project_metadata.project_id_prefix' ${{ env.OPS_FILE_PATH }})
          echo "PROJECT_ID_FROM_FILE=${PROJECT_ID_PREFIX}" >> $GITHUB_ENV
          
          CONTEXT_LABEL=$(jq -r '.project_metadata.context_label' ${{ env.OPS_FILE_PATH }})
          echo "CONTEXT_LABEL_FROM_FILE=${CONTEXT_LABEL}" >> $GITHUB_ENV
          
          ASSIGNEE=$(jq -r '.project_metadata.default_assignee' ${{ env.OPS_FILE_PATH }})
          echo "ASSIGNEE_FROM_FILE=${ASSIGNEE}" >> $GITHUB_ENV
          
          TARGET_DIR_PATH=$(jq -r --arg projid "$PROJECT_ID_PREFIX" '.[$projid].dir_path' ${{ env.PROJECT_MAPPINGS_FILE }})
          echo "TARGET_DIR_PATH=${TARGET_DIR_PATH}" >> $GITHUB_ENV

      - name: Generate Timestamp
        id: timestamp
        run: |
          echo "TIMESTAMP=$(date +'%Y-%m-%d_%H%M')" >> $GITHUB_ENV

      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install google-generativeai 

      - name: Run Brief Generation for Review Script
        id: generate-script
        run: |
          TIMESTAMPED_JSON="${TIMESTAMP}${BASE_OUTPUT_JSON}"
          TIMESTAMPED_MD="${TIMESTAMP}${BASE_OUTPUT_MD}"
          echo "TIMESTAMPED_JSON_OUTPUT=${TIMESTAMPED_JSON}" >> $GITHUB_ENV
          echo "TIMESTAMPED_MD_OUTPUT=${TIMESTAMPED_MD}" >> $GITHUB_ENV
          
          python .github/scripts/generate_briefs_for_review.py \
            --ops_file "$OPS_FILE_PATH" \
            --project_id_cli_arg "$PROJECT_ID_FROM_FILE" \
            --context_label "$CONTEXT_LABEL_FROM_FILE" \
            --assignee "$ASSIGNEE_FROM_FILE" \
            --prompt_template_path "$PROMPT_TEMPLATE_PATH" \
            --project_mappings_file "$PROJECT_MAPPINGS_FILE" \
            --model_name "$GEMINI_MODEL" \
            --output_json_file "$TIMESTAMPED_JSON" \
            --output_md_file "$TIMESTAMPED_MD"

      - name: Prepare and Move Generated Files
        run: |
          DESTINATION_DIR="${TARGET_DIR_PATH}/Generated Briefs"
          mkdir -p "$DESTINATION_DIR"
          mv "$TIMESTAMPED_JSON_OUTPUT" "$DESTINATION_DIR/"
          mv "$TIMESTAMPED_MD_OUTPUT" "$DESTINATION_DIR/"

      - name: Commit Generated Briefs
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "feat(autogen): Add generated briefs for $PROJECT_ID_FROM_FILE [skip ci]"
          commit_user_name: "Chiron Guild Scribe [bot]"
          commit_user_email: "actions@github.com"
          file_pattern: "${TARGET_DIR_PATH}/Generated Briefs/*"
