# .github/workflows/log-op-to-registry.yml

name: Log Guild Op to Registry on Issue Close

on:
  issues:
    types: [closed]

permissions:
  contents: write
  issues: read

jobs:
  log-to-registry:
    if: >-
      github.event.sender.type != 'Bot' &&
      contains(github.event.issue.labels.*.name, 'guild-op') &&
      !contains(github.event.issue.labels.*.name, 'rapid-log')
    runs-on: ubuntu-latest
    permissions:
      contents: read # This workflow only needs to READ the issue

    steps:
      - name: Check out main branch
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Update Operative Registry
        # Pass the entire issue object as a single, safe JSON string
        env:
          ISSUE_PAYLOAD: ${{ toJSON(github.event.issue) }}
        run: |
          python .github/scripts/update_registry.py
          
      - name: Commit and push registry changes
        run: |
          REGISTRY_FILE_PATH="_Admin & Core Docs/registry/operative_registry.json"
          git config user.name "Chiron Guild Bot"
          git config user.email "actions@github.com"
          
          if ! git diff --quiet "$REGISTRY_FILE_PATH"; then
            git add "$REGISTRY_FILE_PATH"
            git commit -m "Forge Seal: Logged Guild Op #${{ github.event.issue.number }} to Registry"
            git push
            echo "Operative Registry updated successfully."
          else
            echo "No changes detected in the registry file. Skipping commit."
          fi
