
name: Log Guild Op to Registry on Issue Close

on:
  issues:
    types: [closed]

permissions:
  contents: write # To commit and push the updated registry file
  issues: read   # To fetch details from the closed issue

jobs:
  log-to-registry:
    runs-on: ubuntu-latest
    if: "contains(github.event.issue.labels.*.name, 'guild-op')" # IMPORTANT: Only run for issues with the 'guild-op' label

    steps:
      - name: Check out main branch
        uses: actions/checkout@v4
        with:
          ref: main # We need to update the registry file on the main branch

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Get Closed Issue Details
        id: get_issue_details
        run: |
          echo '${{ toJSON(github.event.issue) }}' > issue_payload.json
          {
            echo 'issue_number<<EOF'
            jq -r .number issue_payload.json
            echo 'EOF'

            echo 'issue_title<<EOF'
            jq -r .title issue_payload.json
            echo 'EOF'

            echo 'issue_body<<EOF'
            jq -r .body issue_payload.json
            echo 'EOF'
            
            echo 'assignees<<EOF'
            jq -c .assignees issue_payload.json 
            echo 'EOF'

            echo 'labels<<EOF'
            jq -c .labels issue_payload.json 
            echo 'EOF'

            echo 'issue_url<<EOF'
            jq -r .html_url issue_payload.json
            echo 'EOF'

            echo 'closed_at<<EOF'
            jq -r .closed_at issue_payload.json
            echo 'EOF'
          } >> "$GITHUB_ENV"

      - name: Update Operative Registry
        run: |
          python .github/scripts/update_registry.py \
            --issue-number "${{ env.issue_number }}" \
            --issue-title "${{ env.issue_title }}" \
            --issue-body "$(cat issue_body_content.md)" \
            --assignees '${{ env.assignees }}' \
            --labels '${{ env.labels }}' \
            --issue-url "${{ env.issue_url }}" \
            --closed-at "${{ env.closed_at }}"

      - name: Commit and push registry changes
        run: |
          # Define the file path with quotes to handle spaces
          REGISTRY_FILE_PATH="_Admin & Core Docs/registry/operative_registry.json"

          git config user.name "Chiron Guild Bot"
          git config user.email "actions@github.com"
          
          # Use the quoted variable to check for changes and add the file
          if ! git diff --quiet "$REGISTRY_FILE_PATH"; then
            git add "$REGISTRY_FILE_PATH"
            git commit -m "Forge Seal: Logged Guild Op #${{ env.issue_number }} to Registry"
            git push
            echo "Operative Registry updated successfully."
          else
            echo "No changes detected in the registry file. Skipping commit."
          fi
