name: PRODUCTION - ONE-TIME - Backfill and Enrich Registry

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  backfill-dry-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install google-generativeai

      - name: Run Backfill and Enrichment Script
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: |
          python .github/scripts/perform_registry_backfill.py \
            --operative-name "Kin-Caid" \
            --repo-url "${{ github.server_url }}/${{ github.repository }}" \
            --registry-file "_Admin & Core Docs/registry/operative_registry.json"
      
      - name: Upload Generated Registry for Inspection
        uses: actions/upload-artifact@v4
        with:
          name: generated-registry-for-review
          path: _Admin & Core Docs/registry/operative_registry.json