name: Update Operative Registry on Guild Seal Issue Close

on:
  issues:
    types: [closed]

jobs:
  update-registry:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Update operative registry
        run: |
          python .github/scripts/update_registry.py \
            --issue-number "${{ github.event.issue.number }}" \
            --issue-title "${{ github.event.issue.title }}" \
            --issue-body "${{ github.event.issue.body }}" \
            --assignees "${{ toJson(github.event.issue.assignees) }}" \
            --labels "${{ toJson(github.event.issue.labels) }}" \
            --issue-url "${{ github.event.issue.html_url }}" \
            --closed-at "${{ github.event.issue.closed_at }}"
      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add registry/operative_registry.json
          git commit -m "Auto-update registry: Guild Seal for #${{ github.event.issue.number }}"
          git push
