name: Update Operative Registry on Guild Seal Issue Close

on:
  issues:
    types: [closed]

permissions:
  contents: write
  pull-requests: write

jobs:
  update-registry:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set environment variables
        run: |
          echo "ISSUE_BODY<<EOF" >> $GITHUB_ENV
          echo "${{ github.event.issue.body }}" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Update operative registry
        run: |
          python .github/scripts/update_registry.py \
            --issue-number "${{ github.event.issue.number }}" \
            --issue-title "${{ github.event.issue.title }}" \
            --issue-body "${ISSUE_BODY}" \
            --assignees '${{ toJson(github.event.issue.assignees) }}' \
            --labels '${{ toJson(github.event.issue.labels) }}' \
            --issue-url "${{ github.event.issue.html_url }}" \
            --closed-at "${{ github.event.issue.closed_at }}"

      - name: Stage registry changes
        run: git add registry/operative_registry.json

      - name: Debug git remote and user
        run: |
          git remote -v
          git config --get user.name
          git config --get user.email

      - name: Show git status and diff
        run: |
          git status
          git diff

      - name: Show registry file contents
        run: cat registry/operative_registry.json

      - name: Create pull request for registry update
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "Auto-update registry: Guild Seal for #${{ github.event.issue.number }}"
          branch: "auto/registry-update-issue-${{ github.event.issue.number }}"
          title: "Auto-update registry: Guild Seal for #${{ github.event.issue.number }}"
          body: |
            This PR was automatically generated by the workflow to update the operative registry for Issue #${{ github.event.issue.number }}.
          labels: "automated,registry-update"
          delete-branch: true
          token: ${{ secrets.PAT_TOKEN }}
